# Generated by Django 3.0.4 on 2020-03-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kobe', '0002_kobepost_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kobepost',
            name='address',
        ),
    ]
