# Generated by Django 3.0.4 on 2020-03-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobe', '0005_auto_20200313_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='kobepost',
            name='summitTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
