# Generated by Django 3.0.4 on 2020-03-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobe', '0006_kobepost_summittime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kobepost',
            name='summitTime',
        ),
        migrations.AlterField(
            model_name='kobepost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
