# Generated by Django 3.0.4 on 2020-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobe', '0007_auto_20200313_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='kobepost',
            name='summitTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kobepost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
