# Generated by Django 3.0.4 on 2020-03-14 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kobe', '0008_auto_20200313_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kobepost',
            name='summitTime',
        ),
        migrations.AddField(
            model_name='kobepost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='kobepost',
            name='postTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上傳照片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kobepost',
            name='content',
            field=models.TextField(verbose_name='發文內容'),
        ),
        migrations.AlterField(
            model_name='kobepost',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='暱稱'),
        ),
    ]
