# Generated by Django 3.0.4 on 2020-03-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobe', '0009_auto_20200314_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kobepost',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='暱稱（選填）'),
        ),
        migrations.AlterField(
            model_name='kobepost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='上傳照片'),
        ),
        migrations.AlterField(
            model_name='kobepost',
            name='postTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
