# Generated by Django 3.0.4 on 2020-03-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kobe', '0010_auto_20200315_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kobepost',
            name='postTime',
        ),
    ]
