# Generated by Django 3.0.4 on 2020-03-14 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kobe', '0011_remove_kobepost_posttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='kobepost',
            name='postTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
